---
- hosts: all

  vars_files:
    - config.yml

  # roles:
  #   - role: elliotweiser.osx-command-line-tools
  #   - role: geerlingguy.mac.homebrew
  #     tags: ['homebrew']
  #   - role: geerlingguy.mac.dock
  #     when: configure_dock
  #     tags: ['dock']

  tasks:
    # - import_tasks: tasks/extra-packages.yml
    #   tags: ['extra-packages']
    # 
    # - import_tasks: tasks/visual-studio-code.yml
    #   when: configure_visual_studio_code
    #   tags: ['visual-studio-code']

    # - import_tasks: tasks/iterm.yml
    #   tags: ['iterm']
