---
- name: Installing zsh
  command: "brew install zsh"

- name: Installing antibody
  command: "curl -sfL git.io/antibody | sh -s - -b /usr/local/bin"

- name: Setting ZSH as the default shell environment
  command: "sudo sh -c \"echo $(which zsh) >> /etc/shells\""

- name: Setting ZSH as the default shell environment 2
  command: "chsh -s \"$(which zsh)\""
